using System;
using wyk.basic;

namespace wyk.db
{
    /// <summary>
    /// 表适配器描述
    /// 表名:table_demo
    /// 描述:table demo description
    /// Auto generated by wyk.db.DBTableManager at 2018-02-26 15:37
    /// </summary>
    [DBTable("table_demo", "table demo description")]
    public class DBTableDemo : DBTable
    {
        /// <summary>
        /// bit列
        /// </summary>
        [DBColumn("col_bit", DBDataType.Bit, 0, 0, "true", true, false, false, "bit列", false)]
        public bool col_bit = true;

        /// <summary>
        /// byte列
        /// </summary>
        [DBColumn("col_byte", DBDataType.Byte, 0, 0, "", true, false, false, "byte列", false)]
        public byte col_byte = 0;

        /// <summary>
        /// short列
        /// </summary>
        [DBColumn("col_short", DBDataType.Short, 0, 0, "4", true, false, false, "short列", true)]
        public short col_short = 4;

        /// <summary>
        /// integer列
        /// </summary>
        [DBColumn("col_integer", DBDataType.Integer, 0, 0, "", false, true, false, "integer列", false)]
        public int col_integer = 0;

        /// <summary>
        /// long列
        /// </summary>
        [DBColumn("col_long", DBDataType.Long, 0, 0, "15", true, false, false, "long列", false)]
        public long col_long = 15;

        /// <summary>
        /// numeric列
        /// </summary>
        [DBColumn("col_numeric", DBDataType.Numeric, 12, 4, "5.2", true, false, false, "numeric列", false)]
        public double col_numeric = 5.2;

        /// <summary>
        /// varchar列
        /// </summary>
        [DBColumn("col_varchar", DBDataType.Varchar, 50, 0, "", true, false, false, "varchar列", false)]
        public string col_varchar = "";

        /// <summary>
        /// datetime列
        /// </summary>
        [DBColumn("col_datetime", DBDataType.DateTime, 0, 0, "", true, false, false, "datetime列", true)]
        public DateTime col_datetime = DateTimeUtil.defaultTime();

        /// <summary>
        /// binary
        /// </summary>
        [DBColumn("col_binary", DBDataType.Binary, 0, 0, "", true, false, false, "binary列", true)]
        public byte[] col_binary = null;

        public string ColDateTime
        {
            get
            {
                if (DateTimeUtil.isDefaultTime(col_datetime))
                    return "";
                else
                    return col_datetime.ToString("yyyy-MM-dd HH:mm:ss");
            }
            set
            {
                try
                {
                    col_datetime = Convert.ToDateTime(value);
                }
                catch { col_datetime = DateTimeUtil.defaultTime(); }
            }
        }
    }
}
